---
- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: reboot on new kernel
  when: reboot_hint | changed
  command: shutdown -r now "Ansible kernel update applied"
